tasks:
  - name: terraform
    env:
      TF_LOG: DEBUG
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli